# SPDX-FileCopyrightText: 2024 Christina Sørensen, eza contributors
# SPDX-License-Identifier: EUPL-1.2
name: Build Darwin Binary

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-darwin:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build release binary
        run: cargo build --release
      - name: Upload Darwin binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: eza-darwin-binary
          path: target/release/eza
          if-no-files-found: error
